/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 5.7 */
/* /nix/store/zg31qbzi6in2pklhmc647pdp93r5g63f-diamond-3.13-unwrapped/diamond/ispfpga/bin/lin64/scuba -w -n pll1 -lang verilog -synth synplify -bus_exp 7 -bb -arch sa5p00 -type pll -fin 48.00 -fclkop 10.00 -fclkop_tol 10.0 -fclkos 5.00 -fclkos_tol 10.0 -phases 0 -fclkos2 8.00 -fclkos2_tol 10.0 -phases2 0 -phase_cntl STATIC -rst -lock -sticky -fb_mode 1 -fdc /home/akowalski/projekty/twpm/twpm_ecp5/TwPM_toplevel/fpga/puf_2/build/pll1/pll1.fdc  */
/* Fri Feb 23 16:06:39 2024 */


`timescale 1 ns / 1 ps
module pll1 (CLKI, RST, CLKOP, CLKOS, CLKOS2, LOCK)/* synthesis NGD_DRC_MASK=1 */;
    input wire CLKI;
    input wire RST;
    output wire CLKOP;
    output wire CLKOS;
    output wire CLKOS2;
    output wire LOCK;

    wire REFCLK;
    wire CLKOS2_t;
    wire CLKOS_t;
    wire CLKOP_t;

    defparam PLLInst_0.PLLRST_ENA = "ENABLED" ;
    defparam PLLInst_0.INTFB_WAKE = "DISABLED" ;
    defparam PLLInst_0.STDBY_ENABLE = "DISABLED" ;
    defparam PLLInst_0.DPHASE_SOURCE = "DISABLED" ;
    defparam PLLInst_0.CLKOS3_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS3_CPHASE = 0 ;
    defparam PLLInst_0.CLKOS2_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS2_CPHASE = 79 ;
    defparam PLLInst_0.CLKOS_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS_CPHASE = 127 ;
    defparam PLLInst_0.CLKOP_FPHASE = 0 ;
    defparam PLLInst_0.CLKOP_CPHASE = 66 ;
    defparam PLLInst_0.PLL_LOCK_MODE = 2 ;
    defparam PLLInst_0.CLKOS_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOS_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.CLKOP_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOP_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.OUTDIVIDER_MUXD = "DIVD" ;
    defparam PLLInst_0.CLKOS3_ENABLE = "DISABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXC = "DIVC" ;
    defparam PLLInst_0.CLKOS2_ENABLE = "ENABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXB = "DIVB" ;
    defparam PLLInst_0.CLKOS_ENABLE = "ENABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXA = "DIVA" ;
    defparam PLLInst_0.CLKOP_ENABLE = "ENABLED" ;
    defparam PLLInst_0.CLKOS3_DIV = 1 ;
    defparam PLLInst_0.CLKOS2_DIV = 80 ;
    defparam PLLInst_0.CLKOS_DIV = 128 ;
    defparam PLLInst_0.CLKOP_DIV = 67 ;
    defparam PLLInst_0.CLKFB_DIV = 1 ;
    defparam PLLInst_0.CLKI_DIV = 5 ;
    defparam PLLInst_0.FEEDBK_PATH = "CLKOP" ;
    EHXPLLL PLLInst_0 (.CLKI(CLKI), .CLKFB(CLKOP_t), .PHASESEL1(1'b0), 
        .PHASESEL0(1'b0), .PHASEDIR(1'b0), .PHASESTEP(1'b0), 
        .PHASELOADREG(1'b0), .STDBY(1'b0), .PLLWAKESYNC(1'b0), 
        .RST(RST), .ENCLKOP(1'b0), .ENCLKOS(1'b0), .ENCLKOS2(1'b0), 
        .ENCLKOS3(1'b0), .CLKOP(CLKOP_t), .CLKOS(CLKOS_t), .CLKOS2(CLKOS2_t), 
        .CLKOS3(), .LOCK(LOCK), .INTLOCK(), .REFCLK(REFCLK), .CLKINTFB())
             /* synthesis FREQUENCY_PIN_CLKOS2="8.040000" */
             /* synthesis FREQUENCY_PIN_CLKOS="5.025000" */
             /* synthesis FREQUENCY_PIN_CLKOP="9.600000" */
             /* synthesis FREQUENCY_PIN_CLKI="48.000000" */
             /* synthesis ICP_CURRENT="6" */
             /* synthesis LPF_RESISTOR="16" */;

    assign CLKOS2 = CLKOS2_t;
    assign CLKOS = CLKOS_t;
    assign CLKOP = CLKOP_t;


    // exemplar begin
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOS2 8.040000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOS 5.025000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOP 9.600000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKI 48.000000
    // exemplar attribute PLLInst_0 ICP_CURRENT 6
    // exemplar attribute PLLInst_0 LPF_RESISTOR 16
    // exemplar end

endmodule
