TOP = TwPM_Top
SRC = TwPM_Top.v ram/r512x32_512x32.v verilog-lpc-module/lpc_periph.v \
       verilog-tpm-fifo-registers/regs_module.v
QCF = quickfeather.qcf
C16_FREQ = 10000000

include mk/engine.mk
